# --- Core --- #
input-doubleclick-time=200
load-context-menu=yes
load-stats-overlay=no
reset-on-next-file=video-zoom,panscan,video-unscaled,video-rotate,video-align-x,video-align-y,volume

# --- UX --- #
osc=no
title-bar=no
cursor-autohide=500
taskbar-progress=no
snap-window=yes
autofit-larger=80%x80%
autofit-smaller=20%x20%

# --- OSD --- #
osd-bar=no
osd-duration=2000
osd-font=Space Mono
osd-border-size=0.5

# ---- Default Profiles ---- #
profile=high-quality
libplacebo-opts=preset=high_quality
load-auto-profiles=no

# --- Rendering --- #
vo=gpu-next
gpu-api=vulkan
gpu-context=winvk
hwdec=vulkan
vulkan-async-compute=yes
vulkan-async-transfer=yes
vulkan-queue-count=1
vd-lavc-dr=yes

# --- Motion Interpolation --- #
video-sync=display-resample
interpolation=yes
tscale=sphinx
tscale-blur=0.6991556596428412
tscale-radius=1.01
tscale-clamp=0.0
blend-subtitles=yes

# --- Dithering --- #
dither-depth=auto
dither=fruit

# --- Scaling --- #
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=mitchell
linear-downscaling=yes

# --- Anti-Ringing --- #
scale-antiring=0.6
cscale-antiring=0.6

# --- Colorspace --- #
target-colorspace-hint=auto

# --- Deband --- #
deband=yes
deband-iterations=4
deband-threshold=48
deband-range=24
deband-grain=16

# --- Audio ---
replaygain=album
audio-pitch-correction=yes
audio-channels=auto-safe
volume=100
volume-max=150

# --- Subtitles --- #
sub-font=Space Mono
sub-color='#FFF8F9FA'
sub-pos=90
sub-scale=0.8
sub-gauss=1.0
sub-gray=yes
sub-ass-override=no
sub-fix-timing=no
blend-subtitles=yes
sub-border-style=background-box
sub-back-color='#30000000'
sub-shadow-offset=5
sub-margin-x=30
sub-margin-y=30
sub-auto=fuzzy
slang=en,eng
watch-later-options-remove=sub-pos
watch-later-options-remove=osd-margin-y

# --- Playback --- #
keep-open=yes
pause=yes
loop-file=no
loop-playlist=yes
script-opt=osc-playlist_osd=no
script-opt=osc-chapters_osd=no
autocreate-playlist=no
hr-seek=yes
deinterlace=auto
video-aspect-override=no
video-aspect-method=container
demuxer-thread=yes

# --- Streaming --- #
ytdl=yes
ytdl-format=bestvideo[vcodec^=avc1]+bestaudio/best
script-opt=ytdl_hook-try_ytdl_first=yes
script-opt='ytdl_hook-exclude="%.webm$|%.ts$|%.mp3$|%.m3u8$|%.m3u$|%.mkv$|%.mp4$|%.VOB$"'

# --- Profiles --- #
include=~~/profiles/media.profiles.conf
include=~~/profiles/hdr.profiles.conf
include=~~/profiles/shader.profiles.conf
