keybind_allow=no
indicator_icon=pause
indicator_stay=yes
indicator_pos=middle_center

icon_color=#001219
icon_border_color=#FF8232
icon_border_width=3.0
icon_opacity=80

themed_icons=yes
icon_theme=material
theme_style=filled
themed_icon_size=80

mute_indicator=yes
mute_indicator_pos=middle_right
mute_icon_size=60

rectangles_width=20
rectangles_height=60
rectangles_spacing=20

triangle_width=60
triangle_height=60

flash_play_icon=yes
flash_icon_timeout=1
