vidscale=auto
persistent_overlay=yes
redraw_delay=1

font=Space Mono
font_mono=Space Mono
font_color=DEE2E6
font_highlight_color=6ADAFF
font_alert_color=8F86EA
font_size=18
font_padding=1
border_size=0.5

plot_bg_border_width=1.5
plot_bg_border_color=292521
plot_bg_color=000000
plot_color=8F86EA
plot_vsync_ratio=yes
plot_vsync_jitter=yes
plot_perfdata=yes
plot_cache=yes
plot_tonemapping_lut=yes
