# ---------------------- #
# ---- SDR Profiles ---- #
# ---------------------- #

[sdr-display]
profile-desc=Configuration for SDR display
profile-cond=get("user-data/display-info/hdr-supported")=="false"
profile-restore=copy
dither-depth=auto
dither=fruit


# ---------------------- #
# ---- HDR Profiles ---- #
# ---------------------- #

[hdr-display]
profile-desc=Configuration for HDR display
profile-cond=get("user-data/display-info/hdr-supported")=="true"
profile-restore=copy
dither-depth=10
dither=error-diffusion
error-diffusion=sierra-lite
fbo-format=rgba16hf

[hdr-video]
profile-desc=Configuration to enable HDR for PQ or HLG sources
profile-cond=get("user-data/display-info/hdr-supported")=="true" and (p["video-params/gamma"] == "pq" or p["video-params/gamma"] == "hlg")
profile-restore=copy
target-colorspace-hint-mode=source-dynamic
target-trc=pq
target-prim=bt.2020
target-gamut=dci-p3
target-peak=400
target-contrast=inf
gamut-mapping-mode=perceptual
hdr-peak-percentile=99.995
hdr-contrast-recovery=0.30

[hdr-generic]
profile-desc=Generic HDR configuration for content with HDR10/HLG or unknown/fallback Dolby Vision metadata
profile-cond=get("user-data/display-info/hdr-supported")=="true" and (p["video-params/gamma"] == "pq" or p["video-params/gamma"] == "hlg") and (get("video-params/scene-max-r", 0) <= 0) and (get("video-params/scene-max-g", 0) <= 0) and (get("video-params/scene-max-b", 0) <= 0) and (get("current-tracks/video/dolby-vision-profile", 0) ~= 5) and (get("current-tracks/video/dolby-vision-profile", 0) ~= 8) and (get("current-tracks/video/dolby-vision-profile", 0) ~= 9)
profile-restore=copy
hdr-compute-peak=yes

[hdr-dolby-vision]
profile-desc=HDR configuration for content with Dolby Vision 5, 8 or 9 profile
profile-cond=get("user-data/display-info/hdr-supported")=="true" and (get("current-tracks/video/dolby-vision-profile", 0) == 5) or (get("current-tracks/video/dolby-vision-profile", 0) == 8) or (get("current-tracks/video/dolby-vision-profile", 0) == 9)
profile-restore=copy
hdr-compute-peak=no

[hdr-hdr10-plus]
profile-desc=HDR configuration for content with HDR10+ metadata
profile-cond=get("user-data/display-info/hdr-supported")=="true" and (get("video-params/scene-max-r", 0) > 0) or (get("video-params/scene-max-g", 0) > 0) or (get("video-params/scene-max-b", 0) > 0)
profile-restore=copy
tone-mapping=st2094-40
hdr-compute-peak=no
