# ----------------------------- #
# ---- Media Type Profiles ---- #
# ----------------------------- #

[video]
profile-desc=Configuration for video content
profile-cond=p["current-tracks/video"] and not p["current-tracks/video"].image
input-commands=disable-section image
taskbar-progress=yes
profile-restore=copy

[image]
profile-desc=Configuration for images
profile-cond=p["current-tracks/video"] and p["current-tracks/video"].image and not p["current-tracks/video"].albumart
video-recenter=yes
taskbar-progress=no
stop-screensaver=no
prefetch-playlist=yes
video-aspect-override=no
image-display-duration=inf
title=${media-title} [${?width:${width}x${height}}]
input-commands=enable-section image allow-hide-cursor
script-opts-append=modernz-osc_fade_strength=50
script-opts-append=modernz-show_window_title=yes
profile-restore=copy
