# ------------------------- #
# ---- Shader Profiles ---- #
# ------------------------- #

[fsrcnn-x-16]
profile-desc=[scaler] Fast Super-Resolution Convolutional Neural Network Extended [X-16]
glsl-shaders-append="~~/shaders/FSRCNNX_x2_16-0-4-1.glsl"

[fsrcnn-x-16-distort]
profile-desc=[scaler] Fast Super-Resolution Convolutional Neural Network Extended [X-16] [Distort]
glsl-shaders-append="~~/shaders/FSRCNNX_x1_16-0-4-1_distort.glsl"

[artcnn-32-ds]
profile-desc=[scaler] Artoriuz Convolutional Neural Network [32 filters] [De-noise] [Sharpen]
glsl-shaders-append="~~/shaders/ArtCNN_C4F32_DS.glsl"

[ravu-zoom-ar-r3]
profile-desc=[scaler] Rapid and Accurate Video Upscaling [Zoom] [AR-R3]
glsl-shaders-append="~~/shaders/ravu-zoom-ar-r3.hook"

[fsr]
profile-desc=[scaler] AMD FidelityFX Super Resolution
glsl-shaders-append="~~/shaders/FSR.glsl"

[nnedi3-128]
profile-desc=[scaler] Neural Network Edge Directed Interpolation
glsl-shaders-append="~~/shaders/nnedi3-nns128-win8x4.hook"

[krig-bilateral]
profile-desc=[cscaler] KrigBilateral
glsl-shaders-append="~~/shaders/KrigBilateral.glsl"

[ssim-sr]
profile-desc=[scaler-tweaks] SSimSuperResMitchell
glsl-shaders-append="~~/shaders/SSimSuperResMitchell.glsl"

[ssim-ds]
profile-desc=[dscaler] SSimDownscaler
glsl-shaders-append="~~/shaders/SSimDownscaler.glsl"
linear-downscaling=no

[adaptive-sharpen]
profile-desc=[sharpen] Adaptive Sharpen
glsl-shaders-append="~~/shaders/adaptive-sharpen.glsl"

[noise-static]
profile-desc=[deband] Noise Static Luma and Chroma
glsl-shaders-append="~~/shaders/noise_static_luma.hook"
glsl-shaders-append="~~/shaders/noise_static_chroma.hook"
deband-grain=0


# -------------------------------- #
# ---- Video Quality Profiles ---- #
# -------------------------------- #

[sd]
profile-desc=Shader selection for SD content
profile-cond=height<720
profile-restore=copy
glsl-shaders-clr
profile=fsrcnn-x-16-distort
profile=ravu-zoom-ar-r3
profile=krig-bilateral
profile=ssim-sr
profile=ssim-ds

[hd]
profile-desc=Shader selection for 720p content
profile-cond=height==720
profile-restore=copy
glsl-shaders-clr
profile=artcnn-32-ds
profile=krig-bilateral
profile=ssim-sr
profile=ssim-ds

[fhd]
profile-desc=Shader selection for 1080p content
profile-cond=height>720 and height<1440
profile-restore=copy
glsl-shaders-clr
profile=fsrcnn-x-16
profile=krig-bilateral
profile=ssim-sr
profile=ssim-ds

[qhd]
profile-desc=Shader selection for 1440p content
profile-cond=height>=1440 and height<2160
profile-restore=copy
glsl-shaders-clr
profile=fsrcnn-x-16
profile=krig-bilateral
profile=ssim-sr
profile=ssim-ds

[uhd]
profile-desc=Shader selection for 2160p content
profile-cond=height>=2160
profile-restore=copy
glsl-shaders-clr
profile=fsrcnn-x-16
profile=krig-bilateral
profile=ssim-sr
profile=ssim-ds
